### ISSUE TITLE
High resolution puts triangles on octree sides?

### ISSUE THREAD

**Issue by nh2** [hjwdzh/Manifold#4]
Hi, here is a probably simple question about `manifold`:

I have a mesh that with resolution `20000` looks like this:

![image](https://user-images.githubusercontent.com/399535/66880605-eb7cda00-efc3-11e9-8b65-e2f421fa1ad9.png)

But with resolution `500000` it degenerates like this:

![image](https://user-images.githubusercontent.com/399535/66880609-f46dab80-efc3-11e9-9897-3194a0b0de2d.png)

Notice how "cuboid structures" form, instead of the mesh being a continuous surface?

Up close it looks like this from the side:

![image](https://user-images.githubusercontent.com/399535/66880651-1bc47880-efc4-11e9-892b-c18949f5a69e.png)

Do you know why this happens?

**Comment by hjwdzh** [comment]
Can you show me the input?

**Comment by hjwdzh** [comment]
A new release will happen at May 22nd, which possibly will solve meshing problems in the current software.

**Comment by hjwdzh** [comment]
Check this one.

https://github.com/hjwdzh/ManifoldPlus
