### ISSUE TITLE
Download of preprocessed data

### ISSUE THREAD

**Issue by raphaelsulzer** [hjwdzh/Manifold#7]
Hi, and thanks for this valuable software.

It seems like the download links for the preprocessed data provided in http://download.cs.stanford.edu/orion/Shapenet_Manifold/categories.txt are all broken.

Is the proprocessed data still available somewhere?

**Comment by hjwdzh** [comment]
Our stupid server is limited with disk space so I delete them. You will need to process them yourself.

**Comment by shrirangsp** [comment]
> Our stupid server is limited with disk space so I delete them. You will need to process them yourself.

I cannot download the dataset from the given link. Kindly provide an updated link or another way I can access the dataset.
