### ISSUE TITLE
cannot handle a single plane & artifacts

### ISSUE THREAD

**Issue by Colin97** [hjwdzh/Manifold#8]
Thanks for the useful implementation. 

However, it seems that sometimes the code cannot handle the single planes, where the cubes failed to intersect with the plane.
![Screenshot from 2020-04-19 23-51-44](https://user-images.githubusercontent.com/16759292/79722347-c03bb600-8298-11ea-9696-2bc74214f029.png)

Also, there seems to be some strange artifacts.
Input:
![Screenshot from 2020-04-19 23-49-23](https://user-images.githubusercontent.com/16759292/79722213-8074ce80-8298-11ea-94b6-3f4aae7c0a60.png)

Sharp output without projection:
![Screenshot from 2020-04-19 23-49-19](https://user-images.githubusercontent.com/16759292/79722244-8b2f6380-8298-11ea-956f-0b76cede98a7.png)
Is there any explanation for the artifacts?

**Comment by hjwdzh** [comment]
Will release a new version handle all problems at May 22nd.

**Comment by jtorresfabra** [comment]
I'm experiencing similar issues, eagerly waiting to test the new version! Is it happening today? Thanks a lot for sharing your work :)

**Comment by hjwdzh** [comment]
Yes I will. approx. 4-5 hrs later.

**Comment by hjwdzh** [comment]
Check this one:

https://github.com/hjwdzh/ManifoldPlus
